name: CI/CD Pipeline

on:
  push:
    branches:
      - Basic_APIs

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up 17 JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: JiteshJitz
          server-password: ${{ secrets.ACCESS_TOKEN_SECRET }}
          overwrite-settings: true
          job-status: success

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: sudo docker build -t djinoworld-app:${{ github.sha }} .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ec2-3-99-182-61.ca-central-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull djinoworld-app:${{ github.sha }}
            docker run -d --name djinoworld-container -p 8080:8080 djinoworld-app:${{ github.sha }}