name: CI/CD Pipeline

on:
  push:
    branches:
      - Basic_APIs

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Amazon Corretto 17 JDK
        uses: actions/setup-java@v2
        with:
          java-version: 'corretto-17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t djinoworld-app:${{ github.sha }} .