name: CI/CD Pipeline

on:
  push:
    branches:
      - Basic_APIs

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up 17 JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: JiteshJitz
          server-password: ${{ secrets.ACCESS_TOKEN_SECRET }}
          overwrite-settings: true
          job-status: success

      - name: Build with Maven
        run: mvn clean package

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t djinoworld-app:${{ github.sha }} .
          docker tag djinoworld-app:${{ github.sha }} docker.io/jiteshru/djinoworld-app:${{ github.sha }}
          docker push docker.io/jiteshru/djinoworld-app:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-35-183-26-184.ca-central-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull docker.io/your-docker-username/djinoworld-app:${{ github.sha }}
            docker run -d --name djinoworld-container -p 8080:8080 docker.io/your-docker-username/djinoworld-app:${{ github.sha }}
